### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by Lavhe** [shiv19/nativescript-tfjs-sample#1]
The Android Gradle plugin supports only Crashlytics Gradle plugin version 1.25.4 and higher. Project 'tFlow' is using version 1.25.1.

**Comment by shiv19** [comment]
Do a search in npm_modules and platforms folder, and change 1.25.1 to 1.25.4,

It should work fine after that. 

The face detection part of latest plugin firebase is broken, which is why I'm using an older verison of plugin firebase. 

Once that is fixed, I'll update it in this repo.
